import Foundation

enum CourseMathExamples {
    struct Example: Sendable { let title: String; let content: String }
    static let all: [Example] = [
        .init(title: "Functions and Input/Output", content: "math: Function notation\nf(x) = 5x - 2\nf(1) =\nf(2) =\nf(3) =\nf(4) =\nf(5) =\nf(6) =\n\nmath: Quadratic and exponential\nq(x) = -2x^2 + 8x + 3\nq(2) =\np(t) = 75(1.035)^t\np(6) =\n\n// A function's call shows the input substituted into its rule. Change a rule and every later call updates."),
        .init(title: "Fractions, Rates and Budgets", content: "math: Fractions and percentages\n3/4 + 2/3 =\ngcd(12, 18) =\nlcm(4, 3) =\nsum(350, 125, 30, 150, 40, 40) =\npercentchange(80, 100) =\n140 m/s to km/h =\n25 mph to ft/s =\n\n// percentchange returns a decimal rate: 0.25 means 25%. Unit conversions keep a unit suffix. gcd/lcm help find common denominators."),
        .init(title: "Data Summaries", content: "math: Typical values and spread\nmean(2, 4, 4, 4, 5, 5, 7, 9) =\nmedian(2, 4, 4, 4, 5, 5, 7, 9) =\nmode(2, 4, 4, 4, 5, 5, 7, 9) =\nstdev(2, 4, 4, 4, 5, 5, 7, 9) =\nstdevp(2, 4, 4, 4, 5, 5, 7, 9) =\npercentile(0.75, 10, 20, 30, 40) =\npercentrank(20, 10, 20, 30, 40) =\n\n// stdev is the sample standard deviation used in class; stdevp is population. percentile takes k first, then data; it interpolates inclusively. percentrank counts values <= the input. mode uses the smallest tied mode and errors if nothing repeats."),
        .init(title: "Savings and Loan Payments", content: "math: Excel-style payments and savings\nrate = 4.2% / 12\nmonths = 10 * 12\nloan = 2800\npayment = pmt(rate, months, loan)\nabs(payment) * months - loan =\nfv(0.95%/12, 5*12, -210) =\nfv(1.5%/12, 12, -350, -1000) =\npmt(1.5%/12, 12, -1000, 5000) =\ncompound(2000, 2%, 10, 12) =\n\n// Rate is PER PAYMENT PERIOD; monthly rates divide annual rates by 12. Periods multiply years by 12. Cash out is negative, cash in positive, matching Excel. PMT/FV/PV accept an optional fifth argument: 0=end of period, 1=beginning. Payments assume constant rate and amounts, excluding fees/taxes."),
        .init(title: "Slope, Vertex and Real Roots", content: "math: Features of functions\nslope(0, 32000, 1, 33600) =\nvertexx(-2, 8) =\nvertexy(-2, 8, 3) =\ndiscriminant(1, -5, 6) =\nquadraticroot(1, -5, 6, -1) =\nquadraticroot(1, -5, 6, 1) =\ngrowth(32000, 5%, 5) =\n\n// For ax^2+bx+c, vertexx=-b/(2a). quadraticroot's last input is -1 for the smaller root, 1 for the larger. No real roots or a=0 reports Check expression. growth is initial*(1+rate)^periods."),
        .init(title: "Systems and Break-even", content: "math: Solve two linear equations\n// 2x + y = 8; x - y = 1\nx = systemx(2, 1, 8, 1, -1, 1)\ny = systemy(2, 1, 8, 1, -1, 1)\n2x + y =\nx - y =\n\nmath: Break-even\n// Revenue = 10.893x + 217.7; cost = 5.8929x + 5803.9\nunits = systemx(10.893, -1, -217.7, 5.8929, -1, -5803.9)\nceil(units) =\n10.893 * units + 217.7 =\n\n// Six inputs encode ax+by=c, dx+ey=f. Parallel/coincident or numerically degenerate systems report Check expression. Round UP for a whole number of units."),
        .init(title: "Trendlines and Predictions", content: "math: Linear trend\nm = regslope(1, 3, 2, 5, 3, 7, 4, 9)\nb = regintercept(1, 3, 2, 5, 3, 7, 4, 9)\npredict(x) = m*x + b\npredict(5) =\nrsquared(1, 3, 2, 5, 3, 7, 4, 9) =\n\nmath: Quadratic and exponential fits\nquadfit_a(-1, 6, 0, 3, 1, 4, 2, 9) =\nquadfit_b(-1, 6, 0, 3, 1, 4, 2, 9) =\nquadfit_c(-1, 6, 0, 3, 1, 4, 2, 9) =\nexpfit_a(0, 2, 1, 6, 2, 18) =\nexpfit_b(0, 2, 1, 6, 2, 18) =\n\n// Inputs are alternating x,y pairs. Quadratic fits y=ax^2+bx+c. Exponential fits y=a*b^x by least squares on ln(y), so y must be positive. A fit does not establish causation or guarantee extrapolation."),
        .init(title: "Probability, Confidence and Logic", content: "math: Class confidence formula\nprobability(114, 715) =\nmargin(200) =\ncilower(72, 200) =\nciupper(72, 200) =\ncisample(3%) =\n\nmath: Logic\nand(gt(5, 2), lt(3, 8)) =\nor(eq(1, 2), eq(2, 2)) =\nnot(0) =\n\n// Class approximation: p +/- 1/sqrt(n), NOT an exact statistical interval. Bounds are not clipped to [0,1]; answers and margins are decimal rates. cisample rounds up the n needed for this approximation. Logic uses 1=true, 0=false. Functions evaluate every input (no short-circuit).")
    ]
}
