import Foundation

struct MathReferenceEntry: Identifiable, Sendable {
    let category: String
    let names: [String]
    let syntax: String
    let detail: String
    let example: String
    var id: String { syntax }
    func matches(_ query: String) -> Bool {
        query.isEmpty || [category, syntax, detail, example].contains { $0.localizedCaseInsensitiveContains(query) }
    }
}

enum MathReferenceCatalog {
    static let entries: [MathReferenceEntry] = [
        .init(category: "Getting started", names: [], syntax: "Math sections, operators and constants", detail: "Start with math. End queries in =; full-line // comments are ignored. Operators: + − * × / ÷ ^ % of. Powers associate right to left; implicit multiplication (5x, 3(x+1)) has normal multiply/divide precedence. Constants: pi/π, tau=2π, e. Built-ins ignore case. Commas separate arguments; use ungrouped numbers inside calls. Answers show up to six decimals.", example: "math\n2 + 3 * 4 =\n2^3^2 =\n100 + 15% =\n50% of 240 ="),
        .init(category: "Getting started", names: [], syntax: "Variables and custom functions", detail: "Define before calling. Function parameters are local; other variables use values at the calling line. Calls show substitution and result. Up to 16 parameters.", example: "math\ncoffee = 4.50\npeople = 6\ncoffee * people =\nf(x) = 5x - 2\nf(4) =\narea(w,h) = w*h\narea(3,4) ="),
        .init(category: "Roots and rounding", names: ["sqrt"], syntax: "sqrt(x)", detail: "Square/cube root, absolute value, upward/downward rounding, nearest (ties away from zero), or toward zero.", example: "math\nsqrt(144) ="),
        .init(category: "Roots and rounding", names: ["cbrt"], syntax: "cbrt(x)", detail: "Square/cube root, absolute value, upward/downward rounding, nearest (ties away from zero), or toward zero.", example: "math\ncbrt(-125) ="),
        .init(category: "Roots and rounding", names: ["abs"], syntax: "abs(x)", detail: "Square/cube root, absolute value, upward/downward rounding, nearest (ties away from zero), or toward zero.", example: "math\nabs(-17) ="),
        .init(category: "Roots and rounding", names: ["ceil"], syntax: "ceil(x)", detail: "Square/cube root, absolute value, upward/downward rounding, nearest (ties away from zero), or toward zero.", example: "math\nceil(4.01) ="),
        .init(category: "Roots and rounding", names: ["floor"], syntax: "floor(x)", detail: "Square/cube root, absolute value, upward/downward rounding, nearest (ties away from zero), or toward zero.", example: "math\nfloor(-4.01) ="),
        .init(category: "Roots and rounding", names: ["round"], syntax: "round(x)", detail: "Square/cube root, absolute value, upward/downward rounding, nearest (ties away from zero), or toward zero.", example: "math\nround(2.5) ="),
        .init(category: "Roots and rounding", names: ["trunc"], syntax: "trunc(x)", detail: "Square/cube root, absolute value, upward/downward rounding, nearest (ties away from zero), or toward zero.", example: "math\ntrunc(-4.9) ="),
        .init(category: "Logarithms and powers", names: ["log"], syntax: "log(x[,base])", detail: "log/log10 use base 10; log(x,base) accepts a base. log2 uses base 2, ln base e, exp(x)=e^x, pow(a,b)=a^b.", example: "math\nlog(1000) ="),
        .init(category: "Logarithms and powers", names: ["log10"], syntax: "log10(x)", detail: "log/log10 use base 10; log(x,base) accepts a base. log2 uses base 2, ln base e, exp(x)=e^x, pow(a,b)=a^b.", example: "math\nlog10(1000) ="),
        .init(category: "Logarithms and powers", names: ["log2"], syntax: "log2(x)", detail: "log/log10 use base 10; log(x,base) accepts a base. log2 uses base 2, ln base e, exp(x)=e^x, pow(a,b)=a^b.", example: "math\nlog2(256) ="),
        .init(category: "Logarithms and powers", names: ["ln"], syntax: "ln(x)", detail: "log/log10 use base 10; log(x,base) accepts a base. log2 uses base 2, ln base e, exp(x)=e^x, pow(a,b)=a^b.", example: "math\nln(e) ="),
        .init(category: "Logarithms and powers", names: ["exp"], syntax: "exp(x)", detail: "log/log10 use base 10; log(x,base) accepts a base. log2 uses base 2, ln base e, exp(x)=e^x, pow(a,b)=a^b.", example: "math\nexp(ln(7)) ="),
        .init(category: "Logarithms and powers", names: ["pow"], syntax: "pow(a,b)", detail: "log/log10 use base 10; log(x,base) accepts a base. log2 uses base 2, ln base e, exp(x)=e^x, pow(a,b)=a^b.", example: "math\npow(2,3) ="),
        .init(category: "Trigonometry", names: ["sin"], syntax: "sin(x)", detail: "Angles are radians. rad(degrees) converts to radians; deg(radians) converts to degrees. Inverse functions return radians; atan2(y,x) preserves the quadrant.", example: "math\nsin(pi/2) ="),
        .init(category: "Trigonometry", names: ["cos"], syntax: "cos(x)", detail: "Angles are radians. rad(degrees) converts to radians; deg(radians) converts to degrees. Inverse functions return radians; atan2(y,x) preserves the quadrant.", example: "math\ncos(pi) ="),
        .init(category: "Trigonometry", names: ["tan"], syntax: "tan(x)", detail: "Angles are radians. rad(degrees) converts to radians; deg(radians) converts to degrees. Inverse functions return radians; atan2(y,x) preserves the quadrant.", example: "math\ntan(rad(45)) ="),
        .init(category: "Trigonometry", names: ["asin"], syntax: "asin(x)", detail: "Angles are radians. rad(degrees) converts to radians; deg(radians) converts to degrees. Inverse functions return radians; atan2(y,x) preserves the quadrant.", example: "math\nasin(0.5) ="),
        .init(category: "Trigonometry", names: ["acos"], syntax: "acos(x)", detail: "Angles are radians. rad(degrees) converts to radians; deg(radians) converts to degrees. Inverse functions return radians; atan2(y,x) preserves the quadrant.", example: "math\nacos(0.5) ="),
        .init(category: "Trigonometry", names: ["atan"], syntax: "atan(x)", detail: "Angles are radians. rad(degrees) converts to radians; deg(radians) converts to degrees. Inverse functions return radians; atan2(y,x) preserves the quadrant.", example: "math\natan(1) ="),
        .init(category: "Trigonometry", names: ["arcsin"], syntax: "arcsin(x)", detail: "Angles are radians. rad(degrees) converts to radians; deg(radians) converts to degrees. Inverse functions return radians; atan2(y,x) preserves the quadrant.", example: "math\narcsin(0.5) ="),
        .init(category: "Trigonometry", names: ["arccos"], syntax: "arccos(x)", detail: "Angles are radians. rad(degrees) converts to radians; deg(radians) converts to degrees. Inverse functions return radians; atan2(y,x) preserves the quadrant.", example: "math\narccos(0.5) ="),
        .init(category: "Trigonometry", names: ["arctan"], syntax: "arctan(x)", detail: "Angles are radians. rad(degrees) converts to radians; deg(radians) converts to degrees. Inverse functions return radians; atan2(y,x) preserves the quadrant.", example: "math\narctan(1) ="),
        .init(category: "Trigonometry", names: ["atan2"], syntax: "atan2(y,x)", detail: "Angles are radians. rad(degrees) converts to radians; deg(radians) converts to degrees. Inverse functions return radians; atan2(y,x) preserves the quadrant.", example: "math\natan2(1,-1) ="),
        .init(category: "Trigonometry", names: ["rad"], syntax: "rad(x)", detail: "Angles are radians. rad(degrees) converts to radians; deg(radians) converts to degrees. Inverse functions return radians; atan2(y,x) preserves the quadrant.", example: "math\nrad(180) ="),
        .init(category: "Trigonometry", names: ["deg"], syntax: "deg(x)", detail: "Angles are radians. rad(degrees) converts to radians; deg(radians) converts to degrees. Inverse functions return radians; atan2(y,x) preserves the quadrant.", example: "math\ndeg(asin(0.5)) ="),
        .init(category: "Hyperbolic functions", names: ["sinh"], syntax: "sinh(x)", detail: "Hyperbolic functions and inverses; acosh requires x ≥ 1; atanh requires −1 < x < 1.", example: "math\nsinh(0) ="),
        .init(category: "Hyperbolic functions", names: ["cosh"], syntax: "cosh(x)", detail: "Hyperbolic functions and inverses; acosh requires x ≥ 1; atanh requires −1 < x < 1.", example: "math\ncosh(0) ="),
        .init(category: "Hyperbolic functions", names: ["tanh"], syntax: "tanh(x)", detail: "Hyperbolic functions and inverses; acosh requires x ≥ 1; atanh requires −1 < x < 1.", example: "math\ntanh(0) ="),
        .init(category: "Hyperbolic functions", names: ["asinh"], syntax: "asinh(x)", detail: "Hyperbolic functions and inverses; acosh requires x ≥ 1; atanh requires −1 < x < 1.", example: "math\nasinh(0) ="),
        .init(category: "Hyperbolic functions", names: ["acosh"], syntax: "acosh(x)", detail: "Hyperbolic functions and inverses; acosh requires x ≥ 1; atanh requires −1 < x < 1.", example: "math\nacosh(1) ="),
        .init(category: "Hyperbolic functions", names: ["atanh"], syntax: "atanh(x)", detail: "Hyperbolic functions and inverses; acosh requires x ≥ 1; atanh requires −1 < x < 1.", example: "math\natanh(0) ="),
        .init(category: "Extrema and distance", names: ["min"], syntax: "min(values...)", detail: "min/max accept one or more values. hypot(a,b)=sqrt(a²+b²).", example: "math\nmin(7, -2, 4) ="),
        .init(category: "Extrema and distance", names: ["max"], syntax: "max(values...)", detail: "min/max accept one or more values. hypot(a,b)=sqrt(a²+b²).", example: "math\nmax(7, -2, 4) ="),
        .init(category: "Extrema and distance", names: ["hypot"], syntax: "hypot(a,b)", detail: "min/max accept one or more values. hypot(a,b)=sqrt(a²+b²).", example: "math\nhypot(5, 12) ="),
        .init(category: "Course equations", names: ["sum", "mean", "average"], syntax: "sum(values...), mean(values...), average(values...)", detail: "Total or arithmetic mean; at least one value", example: "math\nsum(350, 125, 30, 150, 40, 40) =\nmean(2, 4, 4, 4, 5, 5, 7, 9) =\naverage(2,4,6) ="),
        .init(category: "Course equations", names: ["median"], syntax: "median(values...)", detail: "Sorted middle value, or average of middle pair", example: "math\nmedian(1, 3, 5, 7) ="),
        .init(category: "Course equations", names: ["mode"], syntax: "mode(values...)", detail: "Most frequent value; smallest tied mode; error if none repeats", example: "math\nmode(2, 2, 1, 1, 3) ="),
        .init(category: "Course equations", names: ["stdev", "variance"], syntax: "stdev(values...), variance(values...)", detail: "Sample standard deviation/variance, divisor n−1; at least two values", example: "math\nstdev(1, 2, 3) =\nvariance(1, 2, 3) ="),
        .init(category: "Course equations", names: ["stdevp", "variancep"], syntax: "stdevp(values...), variancep(values...)", detail: "Population versions, divisor n", example: "math\nstdevp(2, 4, 4, 4, 5, 5, 7, 9) =\nvariancep(2, 4, 4, 4, 5, 5, 7, 9) ="),
        .init(category: "Course equations", names: ["percentile"], syntax: "percentile(k, values...)", detail: "Inclusive interpolation at rank k(n−1), 0≤k≤1; k comes FIRST, unlike Excel range syntax", example: "math\npercentile(0.75, 10, 20, 30, 40) ="),
        .init(category: "Course equations", names: ["percentrank"], syntax: "percentrank(value, data...)", detail: "Fraction of data values ≤ value; empirical rank, not Excel's interpolated PERCENTRANK", example: "math\npercentrank(20, 10, 20, 30, 40) ="),
        .init(category: "Course equations", names: ["gcd", "lcm"], syntax: "gcd(a,b), lcm(a,b)", detail: "Nonnegative common divisor/multiple; integer inputs with magnitude ≤10¹²", example: "math\ngcd(84, 126) =\nlcm(12, 18) ="),
        .init(category: "Course equations", names: ["percentchange"], syntax: "percentchange(old,new)", detail: "(new−old)/old; old must be nonzero", example: "math\npercentchange(80, 100) ="),
        .init(category: "Course equations", names: ["slope"], syntax: "slope(x1,y1,x2,y2)", detail: "(y2−y1)/(x2−x1); rejects vertical lines", example: "math\nslope(0, 32000, 1, 33600) ="),
        .init(category: "Course equations", names: ["vertexx", "vertexy"], syntax: "vertexx(a,b), vertexy(a,b,c)", detail: "Vertex of ax²+bx+c, x=−b/(2a), y evaluated there; a≠0", example: "math\nvertexx(-2, 8) =\nvertexy(-2, 8, 3) ="),
        .init(category: "Course equations", names: ["discriminant"], syntax: "discriminant(a,b,c)", detail: "b²−4ac", example: "math\ndiscriminant(1, -5, 6) ="),
        .init(category: "Course equations", names: ["quadraticroot"], syntax: "quadraticroot(a,b,c,which)", detail: "Smaller real root for which=−1, larger for which=1; rejects a=0 or negative discriminant; stable formula avoids cancellation", example: "math\nquadraticroot(1, -5, 6, -1) ="),
        .init(category: "Course equations", names: ["systemx", "systemy"], syntax: "systemx(a,b,c,d,e,f), systemy(a,b,c,d,e,f)", detail: "x/y for ax+by=c and dx+ey=f; rejects parallel/coincident or numerically degenerate systems", example: "math\nsystemx(2, 1, 8, 1, -1, 1) =\nsystemy(2, 1, 8, 1, -1, 1) ="),
        .init(category: "Course equations", names: ["growth"], syntax: "growth(initial,rate,periods)", detail: "initial·(1+rate)^periods; rate>−1", example: "math\ngrowth(32000, 5%, 5) ="),
        .init(category: "Course equations", names: ["compound"], syntax: "compound(principal,annualRate,years[,frequency])", detail: "principal·(1+annualRate/frequency)^(frequency·years); default frequency=12; integer frequency>0", example: "math\ncompound(2000, 2%, 10, 12) ="),
        .init(category: "Course equations", names: ["regslope", "regintercept"], syntax: "regslope(x1,y1,x2,y2,...), regintercept(...)", detail: "Linear least-squares y=mx+b; at least two points with distinct x", example: "math\nregslope(1, 3, 2, 5, 3, 7, 4, 9) =\nregintercept(1, 3, 2, 5, 3, 7, 4, 9) ="),
        .init(category: "Course equations", names: ["correlation", "rsquared"], syntax: "correlation(pairs...), rsquared(pairs...)", detail: "Pearson r and r² for linear regression; reject constant x or y", example: "math\ncorrelation(1, 3, 2, 5, 3, 7, 4, 9) =\nrsquared(1, 3, 2, 5, 3, 7, 4, 9) ="),
        .init(category: "Course equations", names: ["expfit_a", "expfit_b"], syntax: "expfit_a(pairs...), expfit_b(pairs...)", detail: "Fit y=a·b^x via linear least squares on ln(y); every y>0", example: "math\nexpfit_a(0, 2, 1, 6, 2, 18) =\nexpfit_b(0, 2, 1, 6, 2, 18) ="),
        .init(category: "Course equations", names: ["quadfit_a", "quadfit_b", "quadfit_c"], syntax: "quadfit_a(pairs...), quadfit_b(pairs...), quadfit_c(pairs...)", detail: "Least-squares y=ax²+bx+c; at least three distinct x; centered/scaled system with pivoting; reject degenerate data", example: "math\nquadfit_a(-1, 6, 0, 3, 1, 4, 2, 9) =\nquadfit_b(-1, 6, 0, 3, 1, 4, 2, 9) =\nquadfit_c(-1, 6, 0, 3, 1, 4, 2, 9) ="),
        .init(category: "Course equations", names: ["probability"], syntax: "probability(successes,total)", detail: "successes/total, integer counts, 0≤successes≤total, total>0", example: "math\nprobability(114, 715) ="),
        .init(category: "Course equations", names: ["margin"], syntax: "margin(n)", detail: "Textbook approximation 1/√n, positive integer n", example: "math\nmargin(200) ="),
        .init(category: "Course equations", names: ["cilower", "ciupper"], syntax: "cilower(successes,n), ciupper(successes,n)", detail: "successes/n ∓ 1/√n; unrounded, not clipped to [0,1]", example: "math\ncilower(72, 200) =\nciupper(72, 200) ="),
        .init(category: "Course equations", names: ["cisample"], syntax: "cisample(margin)", detail: "ceil(1/margin²), 0<margin≤1; sample size for that course approximation", example: "math\ncisample(3%) ="),
        .init(category: "Course equations", names: ["eq", "lt", "le", "gt", "ge"], syntax: "eq(a,b), lt(a,b), le(a,b), gt(a,b), ge(a,b)", detail: "Equal / less / less-or-equal / greater / greater-or-equal; 1 or 0", example: "math\neq(2, 2) =\nlt(5, 2) =\nle(2,2) =\ngt(3,2) =\nge(2,2) ="),
        .init(category: "Course equations", names: ["and", "or", "not"], syntax: "and(values...), or(values...), not(value)", detail: "Boolean numeric inputs must be 0 or 1; all inputs are evaluated, no short circuit", example: "math\nand(gt(5, 2), lt(3, 8)) =\nor(eq(1, 2), eq(2, 2)) =\nnot(0) ="),
        .init(category: "Finance", names: ["pmt"], syntax: "pmt(rate,periods,pv[,fv[,type]])", detail: "Rate is per period: annual/12 for monthly. Cash paid out is negative; received is positive. Optional balance defaults to 0; type 0=end, 1=beginning. Include 0 to skip a balance. Assumes constant rate/payment; no fees or cent-rounding.", example: "math\npmt(0, 12, 1200) ="),
        .init(category: "Finance", names: ["fv"], syntax: "fv(rate,periods,pmt[,pv[,type]])", detail: "Rate is per period: annual/12 for monthly. Cash paid out is negative; received is positive. Optional balance defaults to 0; type 0=end, 1=beginning. Include 0 to skip a balance. Assumes constant rate/payment; no fees or cent-rounding.", example: "math\nfv(0, 12, -100) ="),
        .init(category: "Finance", names: ["pv"], syntax: "pv(rate,periods,pmt[,fv[,type]])", detail: "Rate is per period: annual/12 for monthly. Cash paid out is negative; received is positive. Optional balance defaults to 0; type 0=end, 1=beginning. Include 0 to skip a balance. Assumes constant rate/payment; no fees or cent-rounding.", example: "math\npv(0, 12, -100) ="),
        .init(category: "Finance", names: ["nper"], syntax: "nper(rate,pmt,pv[,fv[,type]])", detail: "Rate is per period: annual/12 for monthly. Cash paid out is negative; received is positive. Optional balance defaults to 0; type 0=end, 1=beginning. Include 0 to skip a balance. Assumes constant rate/payment; no fees or cent-rounding.", example: "math\nnper(0, -100, 1200) ="),
        .init(category: "Units", names: [], syntax: "number unit to unit =", detail: "Length: m/cm/mm/km/in/ft/yd/mi. Mass: g/kg/lb/oz. Volume: ml/l/gal (US). Time: s/min/h. Speed: m/s/km/h/mph/ft/s. Temperature: c/f. Numeric literal input; units must be compatible.", example: "math\n10 km to mi =\n20 c to f =\n140 m/s to km/h ="),
        .init(category: "Limits", names: [], syntax: "Check expression", detail: "Invalid domains/arguments, division by zero or unknown functions report Check expression. Real values only; no complex roots, symbolic solving, charts or spreadsheet cell/range syntax. Confidence intervals use the course approximation p ± 1/√n, without clipping to [0,1].", example: "math\nsqrt(-1) =\n1/0 ="),
    ]
}
